<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
<meta name="viewport" content="width=device-width">
<meta name="theme-color" content="#222" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#222" media="(prefers-color-scheme: dark)"><meta name="generator" content="Hexo 7.0.0">

  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png">
  <link rel="mask-icon" href="/images/logo.svg" color="#222">

<link rel="stylesheet" href="/css/main.css">

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family='Source+Serif+4':300,300italic,400,400italic,700,700italic%7C'JetBrains+Mono':300,300italic,400,400italic,700,700italic&display=swap&subset=latin,latin-ext">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha256-yIDrPSXHZdOZhAqiBP7CKzIwMQmRCJ8UeB8Jo17YC4o=" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.1/animate.min.css" integrity="sha256-PR7ttpcvz8qrF57fur/yAx1qXMFJeJFiA6pSzWi0OIE=" crossorigin="anonymous">

<script class="next-config" data-name="main" type="application/json">{"hostname":"jason5lee.me","root":"/","images":"/images","scheme":"Gemini","darkmode":true,"version":"8.19.1","exturl":false,"sidebar":{"position":"left","display":"post","padding":18,"offset":12},"copycode":{"enable":false,"style":null},"fold":{"enable":false,"height":500},"bookmark":{"enable":false,"color":"#222","save":"auto"},"mediumzoom":false,"lazyload":false,"pangu":false,"comments":{"style":"tabs","active":null,"storage":true,"lazyload":false,"nav":null},"stickytabs":false,"motion":{"enable":true,"async":false,"transition":{"menu_item":"fadeInDown","post_block":"fadeIn","post_header":"fadeInDown","post_body":"fadeInDown","coll_header":"fadeInLeft","sidebar":"fadeInUp"}},"prism":false,"i18n":{"placeholder":"Searching...","empty":"We didn't find any results for the search: ${query}","hits_time":"${hits} results found in ${time} ms","hits":"${hits} results found"}}</script><script src="/js/config.js"></script>

    <meta name="description" content="WARNING: This may be a bad practice. The point of this article is just to share my idea. Exception is a popular feature in many programming languages. Unlike Rust where errors are considered as a retu">
<meta property="og:type" content="article">
<meta property="og:title" content="Simulate exception in async Rust">
<meta property="og:url" content="https://jason5lee.me/2022/03/11/rust-exception-async/index.html">
<meta property="og:site_name" content="Jason5Lee Personal Blog">
<meta property="og:description" content="WARNING: This may be a bad practice. The point of this article is just to share my idea. Exception is a popular feature in many programming languages. Unlike Rust where errors are considered as a retu">
<meta property="og:locale" content="en_US">
<meta property="article:published_time" content="2022-03-11T14:40:23.000Z">
<meta property="article:author" content="Jason5Lee">
<meta property="article:tag" content="rust">
<meta property="article:tag" content="async">
<meta property="article:tag" content="exception">
<meta name="twitter:card" content="summary">


<link rel="canonical" href="https://jason5lee.me/2022/03/11/rust-exception-async/">



<script class="next-config" data-name="page" type="application/json">{"sidebar":"","isHome":false,"isPost":true,"lang":"en","comments":true,"permalink":"https://jason5lee.me/2022/03/11/rust-exception-async/","path":"2022/03/11/rust-exception-async/","title":"Simulate exception in async Rust"}</script>

<script class="next-config" data-name="calendar" type="application/json">""</script>
<title>Simulate exception in async Rust | Jason5Lee Personal Blog</title>
  








  <noscript>
    <link rel="stylesheet" href="/css/noscript.css">
  </noscript>
</head>

<body itemscope itemtype="http://schema.org/WebPage" class="use-motion">
  <div class="headband"></div>

  <main class="main">
    <div class="column">
      <header class="header" itemscope itemtype="http://schema.org/WPHeader"><div class="site-brand-container">
  <div class="site-nav-toggle">
    <div class="toggle" aria-label="Toggle navigation bar" role="button">
    </div>
  </div>

  <div class="site-meta">

    <a href="/" class="brand" rel="start">
      <i class="logo-line"></i>
      <p class="site-title">Jason5Lee Personal Blog</p>
      <i class="logo-line"></i>
    </a>
  </div>

  <div class="site-nav-right">
    <div class="toggle popup-trigger" aria-label="Search" role="button">
    </div>
  </div>
</div>







</header>
        
  
  <aside class="sidebar">

    <div class="sidebar-inner sidebar-overview-active">
      <ul class="sidebar-nav">
        <li class="sidebar-nav-toc">
          Table of Contents
        </li>
        <li class="sidebar-nav-overview">
          Overview
        </li>
      </ul>

      <div class="sidebar-panel-container">
        <!--noindex-->
        <div class="post-toc-wrap sidebar-panel">
        </div>
        <!--/noindex-->

        <div class="site-overview-wrap sidebar-panel">
          <div class="site-author animated" itemprop="author" itemscope itemtype="http://schema.org/Person">
  <p class="site-author-name" itemprop="name">Jason5Lee</p>
  <div class="site-description" itemprop="description">Jason5Lee Personal Blog</div>
</div>
<div class="site-state-wrap animated">
  <nav class="site-state">
      <div class="site-state-item site-state-posts">
        <a href="/archives/">
          <span class="site-state-item-count">6</span>
          <span class="site-state-item-name">posts</span>
        </a>
      </div>
      <div class="site-state-item site-state-categories">
          <a href="/categories/">
        <span class="site-state-item-count">4</span>
        <span class="site-state-item-name">categories</span></a>
      </div>
      <div class="site-state-item site-state-tags">
          <a href="/tags/">
        <span class="site-state-item-count">15</span>
        <span class="site-state-item-name">tags</span></a>
      </div>
  </nav>
</div>
  <div class="cc-license animated" itemprop="license">
    <a href="https://creativecommons.org/licenses/by-sa/4.0/" class="cc-opacity" rel="noopener" target="_blank"><img src="https://cdnjs.cloudflare.com/ajax/libs/creativecommons-vocabulary/2020.11.3/assets/license_badges/small/by_sa.svg" alt="Creative Commons"></a>
  </div>

        </div>
      </div>
    </div>

    
  </aside>


    </div>

    <div class="main-inner post posts-expand">


  


<div class="post-block">
  
  

  <article itemscope itemtype="http://schema.org/Article" class="post-content" lang="en">
    <link itemprop="mainEntityOfPage" href="https://jason5lee.me/2022/03/11/rust-exception-async/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/images/avatar.gif">
      <meta itemprop="name" content="Jason5Lee">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="Jason5Lee Personal Blog">
      <meta itemprop="description" content="Jason5Lee Personal Blog">
    </span>

    <span hidden itemprop="post" itemscope itemtype="http://schema.org/CreativeWork">
      <meta itemprop="name" content="Simulate exception in async Rust | Jason5Lee Personal Blog">
      <meta itemprop="description" content="">
    </span>
      <header class="post-header">
        <h1 class="post-title" itemprop="name headline">
          Simulate exception in async Rust
        </h1>

        <div class="post-meta-container">
          <div class="post-meta">
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar"></i>
      </span>
      <span class="post-meta-item-text">Posted on</span>

      <time title="Created: 2022-03-11 22:40:23" itemprop="dateCreated datePublished" datetime="2022-03-11T22:40:23+08:00">2022-03-11</time>
    </span>
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-folder"></i>
      </span>
      <span class="post-meta-item-text">In</span>
        <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
          <a href="/categories/rust/" itemprop="url" rel="index"><span itemprop="name">rust</span></a>
        </span>
    </span>

  
</div>

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody"><p><strong>WARNING</strong>: This may be a bad practice. The point of this article is just to share my idea.</p>
<p>Exception is a popular feature in many programming languages. Unlike Rust where errors are considered as a return value of the <code>Err</code> case of <code>Result</code>, in these languages errors are thrown like <code>panic</code>. The caller may catch the errors and process them similar to <code>catch_unwind</code> in Rust. Different people may have different preferences on the error handling style, but panic-unwind is always considered a bad practice and should be avoided if possible. So using exception-like error handling in Rust is impossible.</p>
<p>Well, it is possible with async Rust, but we need a little trick. The main idea here is to stop polling the future after an exception is thrown.</p>
<span id="more"></span>
<p>First, we define an exception context, which stores the thrown exception if any.</p>
<figure class="highlight rust"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#[derive(Default)]</span></span><br><span class="line"><span class="keyword">pub</span> <span class="keyword">struct</span> <span class="title class_">ExceptionContext</span> &#123;</span><br><span class="line">    exception: std::cell::Cell&lt;<span class="type">Option</span>&lt;anyhow::Error&gt;&gt;, <span class="comment">// You can change `anyhow::Error` to your exception type.</span></span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">impl</span> <span class="title class_">ExceptionContext</span> &#123;</span><br><span class="line">    <span class="keyword">pub</span> <span class="keyword">fn</span> <span class="title function_">new</span>() <span class="punctuation">-&gt;</span> ExceptionContext &#123;</span><br><span class="line">        std::default::<span class="built_in">Default</span>::<span class="title function_ invoke__">default</span>()</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>For the function that may throw the exception, it needs to accept an argument with type <code>&amp;ExceptionContext</code>. If there is already a context-like type, you can consider embedding this struct into it.</p>
<p>Now, we try to implement the throw function. When an exception is thrown, the exception field will be set, and the code after the throw should not be executed. We can do this by <code>core::future::pending().await</code>.</p>
<figure class="highlight rust"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">impl</span> <span class="title class_">ExceptionContext</span> &#123;</span><br><span class="line">    <span class="keyword">pub</span> <span class="keyword">async</span> <span class="keyword">fn</span> <span class="title function_">throw</span>(&amp;<span class="keyword">self</span>, exception: anyhow::Error) <span class="punctuation">-&gt;</span> ! &#123;</span><br><span class="line">        <span class="keyword">self</span>.exception.<span class="title function_ invoke__">set</span>(<span class="title function_ invoke__">Some</span>(exception));</span><br><span class="line">        core::future::<span class="title function_ invoke__">pending</span>().<span class="keyword">await</span></span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>In an async function with <code>ExceptionContext</code>, if you want to throw an exception, just use the <code>throw</code> method then await the return value.</p>
<figure class="highlight rust"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">async</span> <span class="keyword">fn</span> <span class="title function_">send</span>(ctx: &amp;ExceptionContext, msg: &amp;<span class="type">str</span>, connected: <span class="type">bool</span>) <span class="punctuation">-&gt;</span> <span class="type">usize</span> &#123;</span><br><span class="line">    <span class="keyword">if</span> connected &#123;</span><br><span class="line">        msg.<span class="title function_ invoke__">len</span>()</span><br><span class="line">    &#125; <span class="keyword">else</span> &#123;</span><br><span class="line">        ctx</span><br><span class="line">            .<span class="title function_ invoke__">throw</span>(anyhow::anyhow!(<span class="string">&quot;send error: not connected&quot;</span>))</span><br><span class="line">            .<span class="keyword">await</span></span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>Now, how should we execute the function with exception? We need to prepare a future that wraps the async function result. It polls the inner future until either getting <code>Ready</code> or an exception is set in the context.</p>
<figure class="highlight rust"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br></pre></td><td class="code"><pre><span class="line">pin_project_lite::pin_project! &#123; <span class="comment">// pin-project-lite = &quot;0.2&quot;</span></span><br><span class="line">    <span class="keyword">pub</span> <span class="keyword">struct</span> <span class="title class_">Catching</span>&lt;<span class="symbol">&#x27;a</span>, F&gt; &#123;</span><br><span class="line">        ctx: &amp;<span class="symbol">&#x27;a</span> ExceptionContext,</span><br><span class="line">        <span class="meta">#[pin]</span></span><br><span class="line">        future: F,</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br><span class="line"></span><br><span class="line"><span class="keyword">impl</span>&lt;<span class="symbol">&#x27;a</span>, F: std::future::Future&gt; std::future::Future <span class="keyword">for</span> <span class="title class_">Catching</span>&lt;<span class="symbol">&#x27;a</span>, F&gt; &#123;</span><br><span class="line">    <span class="keyword">type</span> <span class="title class_">Output</span> = anyhow::<span class="type">Result</span>&lt;F::Output&gt;;</span><br><span class="line"></span><br><span class="line">    <span class="keyword">fn</span> <span class="title function_">poll</span>(</span><br><span class="line">        <span class="keyword">self</span>: std::pin::Pin&lt;&amp;<span class="keyword">mut</span> <span class="keyword">Self</span>&gt;,</span><br><span class="line">        cx: &amp;<span class="keyword">mut</span> std::task::Context&lt;<span class="symbol">&#x27;_</span>&gt;,</span><br><span class="line">    ) <span class="punctuation">-&gt;</span> std::task::Poll&lt;<span class="keyword">Self</span>::Output&gt; &#123;</span><br><span class="line">        <span class="keyword">let</span> <span class="variable">this</span> = <span class="keyword">self</span>.<span class="title function_ invoke__">project</span>();</span><br><span class="line">        <span class="keyword">let</span> <span class="variable">p</span> = this.future.<span class="title function_ invoke__">poll</span>(cx);</span><br><span class="line">        <span class="keyword">if</span> <span class="keyword">let</span> <span class="variable">Some</span>(exception) = this.ctx.exception.<span class="title function_ invoke__">take</span>() &#123;</span><br><span class="line">            std::task::Poll::<span class="title function_ invoke__">Ready</span>(<span class="title function_ invoke__">Err</span>(exception))</span><br><span class="line">        &#125; <span class="keyword">else</span> &#123;</span><br><span class="line">            p.<span class="title function_ invoke__">map</span>(<span class="literal">Ok</span>)</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>Then we can implement a catching method that accepts an async function that requires an exception context and returns a <code>Catching</code> future.</p>
<figure class="highlight rust"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">impl</span> <span class="title class_">ExceptionContext</span> &#123;</span><br><span class="line">    <span class="keyword">pub</span> <span class="keyword">fn</span> <span class="title function_">catching</span>&lt;<span class="symbol">&#x27;a</span>, Fu: std::future::Future, F: <span class="title function_ invoke__">Fn</span>(&amp;<span class="symbol">&#x27;a</span> <span class="keyword">Self</span>) <span class="punctuation">-&gt;</span> Fu&gt;(</span><br><span class="line">        &amp;<span class="symbol">&#x27;a</span> <span class="keyword">self</span>,</span><br><span class="line">        f: F,</span><br><span class="line">    ) <span class="punctuation">-&gt;</span> Catching&lt;<span class="symbol">&#x27;a</span>, Fu&gt; &#123;</span><br><span class="line">        Catching &#123;</span><br><span class="line">            ctx: <span class="keyword">self</span>,</span><br><span class="line">            future: <span class="title function_ invoke__">f</span>(<span class="keyword">self</span>),</span><br><span class="line">        &#125;</span><br><span class="line">    &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>Now we can execute a block with exceptions like this.</p>
<figure class="highlight rust"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">#[tokio::main(flavor = <span class="string">&quot;current_thread&quot;</span>)]</span></span><br><span class="line"><span class="keyword">async</span> <span class="keyword">fn</span> <span class="title function_">main</span>() &#123;</span><br><span class="line">    <span class="keyword">let</span> <span class="variable">result</span> = ExceptionContext::<span class="title function_ invoke__">new</span>()</span><br><span class="line">        .<span class="title function_ invoke__">catching</span>(|ctx| <span class="keyword">async</span> <span class="keyword">move</span> &#123;</span><br><span class="line">            <span class="built_in">assert_eq!</span>(<span class="number">5</span>, <span class="title function_ invoke__">send</span>(ctx, <span class="string">&quot;abcde&quot;</span>, <span class="literal">true</span>).<span class="keyword">await</span>);</span><br><span class="line">            <span class="built_in">assert_eq!</span>(<span class="number">3</span>, <span class="title function_ invoke__">send</span>(ctx, <span class="string">&quot;abc&quot;</span>, <span class="literal">true</span>).<span class="keyword">await</span>);</span><br><span class="line">            <span class="title function_ invoke__">send</span>(ctx, <span class="string">&quot;&quot;</span>, <span class="literal">false</span>).<span class="keyword">await</span>;</span><br><span class="line">            <span class="built_in">panic!</span>(<span class="string">&quot;Shouldn&#x27;t reach here cause an exception is thrown&quot;</span>);</span><br><span class="line">        &#125;)</span><br><span class="line">        .<span class="keyword">await</span>;</span><br><span class="line">    <span class="built_in">assert_eq!</span>(result.<span class="title function_ invoke__">unwrap_err</span>().<span class="title function_ invoke__">to_string</span>(), <span class="string">&quot;send error: not connected&quot;</span>);</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>You can find the complete code <a target="_blank" rel="noopener" href="https://play.rust-lang.org/?version=stable&amp;mode=debug&amp;edition=2021&amp;gist=a5c69b3a0c00d1558bbbe50d11c31c72">here</a>. I also made <a target="_blank" rel="noopener" href="https://github.com/Jason5Lee/asynx">a crate</a> to provide a general implementation of<br>
<code>ExceptionContext</code> and a <code>Sync</code> version.</p>
<p>There are pros and cons of this approach. The biggest pro is that it has no panic-unwind. You can use <code>panic = abort</code> while doing exception-style programming. However, there are the following cons.</p>
<ul>
<li>Only supports <code>async</code> function.</li>
<li>The future will be canceled if an exception occurs, <a target="_blank" rel="noopener" href="https://carllerche.com/2021/06/17/six-ways-to-make-async-rust-easier/">which can be problematic</a>.</li>
<li>Exception-style is widely considered bad, especially in the Rust community, so even we can do it without panic-unwind it may still be a bad practice.</li>
</ul>
<p>This is just my idea, whether to use it is up to you.</p>

    </div>

    
    
    

    <footer class="post-footer">
          <div class="reward-container">
  <div>Buy me a coffee</div>
  <button>
    Donate
  </button>
  <div class="post-reward">
      <div>
        <img src="/images/paypal.png" alt="Jason5Lee PayPal">
        <span>PayPal</span>
      </div>
      <div>
        <img src="/images/ethereum.png" alt="Jason5Lee Ethereum">
        <span>Ethereum</span>
      </div>
      <div>
        <img src="/images/bitcoin.png" alt="Jason5Lee Bitcoin">
        <span>Bitcoin</span>
      </div>
      <div>
        <img src="/images/paynow.jpg" alt="Jason5Lee PayNow">
        <span>PayNow</span>
      </div>

  </div>
</div>

          <div class="post-tags">
              <a href="/tags/rust/" rel="tag"># rust</a>
              <a href="/tags/async/" rel="tag"># async</a>
              <a href="/tags/exception/" rel="tag"># exception</a>
          </div>

        

          <div class="post-nav">
            <div class="post-nav-item">
                <a href="/2020/01/11/rust-costumized-trait-object/" rel="prev" title="Customized trait object in Rust">
                  <i class="fa fa-angle-left"></i> Customized trait object in Rust
                </a>
            </div>
            <div class="post-nav-item">
                <a href="/2022/04/12/telegram-bot-rust-azure-function/" rel="next" title="Building a Telegram Bot on Azure Function in Rust">
                  Building a Telegram Bot on Azure Function in Rust <i class="fa fa-angle-right"></i>
                </a>
            </div>
          </div>
    </footer>
  </article>
</div>






</div>
  </main>

  <footer class="footer">
    <div class="footer-inner">

  <div class="copyright">
    &copy; 
    <span itemprop="copyrightYear">2023</span>
    <span class="with-love">
      <i class="fa fa-heart"></i>
    </span>
    <span class="author" itemprop="copyrightHolder">Jason5Lee</span>
  </div>
  <div class="powered-by">Powered by <a href="https://hexo.io/" rel="noopener" target="_blank">Hexo</a> & <a href="https://theme-next.js.org/" rel="noopener" target="_blank">NexT.Gemini</a>
  </div>

    </div>
  </footer>

  
  <div class="back-to-top" role="button" aria-label="Back to top">
    <i class="fa fa-arrow-up fa-lg"></i>
    <span>0%</span>
  </div>

<noscript>
  <div class="noscript-warning">Theme NexT works best with JavaScript enabled</div>
</noscript>


  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js" integrity="sha256-XL2inqUJaslATFnHdJOi9GfQ60on8Wx1C2H8DYiN1xY=" crossorigin="anonymous"></script>
<script src="/js/comments.js"></script><script src="/js/utils.js"></script><script src="/js/motion.js"></script><script src="/js/next-boot.js"></script>

  






  




  

  <script class="next-config" data-name="enableMath" type="application/json">false</script><script class="next-config" data-name="mathjax" type="application/json">{"enable":true,"tags":"none","js":{"url":"https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js","integrity":"sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI="}}</script>
<script src="/js/third-party/math/mathjax.js"></script>



</body>
</html>
